// `yarn add highlight.js`
// `yarn add @highlightjs/vue-plugin`
import "highlight.js/styles/base16/seti-ui.css";
// import "highlight.js/lib/common";
import hljs from "highlight.js/lib/core";
import hljsVuePlugin from "@highlightjs/vue-plugin";

import javascript from "highlight.js/lib/languages/javascript";
import java from "highlight.js/lib/languages/java";
import typescript from "highlight.js/lib/languages/typescript";
import c from "highlight.js/lib/languages/c";
import cpp from "highlight.js/lib/languages/cpp";
import python from "highlight.js/lib/languages/python";
import csharp from "highlight.js/lib/languages/csharp";
import fsharp from "highlight.js/lib/languages/fsharp";
import go from "highlight.js/lib/languages/go";
import rust from "highlight.js/lib/languages/rust";
import php from "highlight.js/lib/languages/php";
import sql from "highlight.js/lib/languages/sql";
import basic from "highlight.js/lib/languages/basic";
import swift from "highlight.js/lib/languages/swift";
import elixir from "highlight.js/lib/languages/elixir";
import scala from "highlight.js/lib/languages/scala";
import ruby from "highlight.js/lib/languages/ruby";
import erlang from "highlight.js/lib/languages/erlang";
import haskell from "highlight.js/lib/languages/haskell";
import kotlin from "highlight.js/lib/languages/kotlin";
import dart from "highlight.js/lib/languages/dart";
import markdown from "highlight.js/lib/languages/markdown";
import protobuf from "highlight.js/lib/languages/protobuf";
import django from "highlight.js/lib/languages/django";
import dockerfile from "highlight.js/lib/languages/dockerfile";
import yaml from "highlight.js/lib/languages/yaml";
import graphql from "highlight.js/lib/languages/graphql";
import latex from "highlight.js/lib/languages/latex";
import matlab from "highlight.js/lib/languages/matlab";
import mathematica from "highlight.js/lib/languages/mathematica";
import bash from "highlight.js/lib/languages/bash";
import xml from "highlight.js/lib/languages/xml";
import json from "highlight.js/lib/languages/json";
import css from "highlight.js/lib/languages/css";
import scss from "highlight.js/lib/languages/scss";

hljs.registerLanguage("javascript", javascript);
hljs.registerLanguage("java", java);
hljs.registerLanguage("typescript", typescript);
hljs.registerLanguage("c", c);
hljs.registerLanguage("cpp", cpp);
hljs.registerLanguage("python", python);
hljs.registerLanguage("csharp", csharp);
hljs.registerLanguage("fsharp", fsharp);
hljs.registerLanguage("go", go);
hljs.registerLanguage("rust", rust);
hljs.registerLanguage("php", php);
hljs.registerLanguage("sql", sql);
hljs.registerLanguage("basic", basic);
hljs.registerLanguage("swift", swift);
hljs.registerLanguage("elixir", elixir);
hljs.registerLanguage("scala", scala);
hljs.registerLanguage("ruby", ruby);
hljs.registerLanguage("erlang", erlang);
hljs.registerLanguage("haskell", haskell);
hljs.registerLanguage("kotlin", kotlin);
hljs.registerLanguage("dart", dart);
hljs.registerLanguage("markdown", markdown);
hljs.registerLanguage("protobuf", protobuf);
hljs.registerLanguage("django", django);
hljs.registerLanguage("dockerfile", dockerfile);
hljs.registerLanguage("yaml", yaml);
hljs.registerLanguage("graphql", graphql);
hljs.registerLanguage("latex", latex);
hljs.registerLanguage("matlab", matlab);
hljs.registerLanguage("mathematica", mathematica);
hljs.registerLanguage("bash", bash);
hljs.registerLanguage("xml", xml);
hljs.registerLanguage("json", json);
hljs.registerLanguage("css", css);
hljs.registerLanguage("scss", scss);

export default ({ app }) => {
  app.use(hljsVuePlugin);
};
